### ISSUE TITLE
Error on launch.

### ISSUE THREAD

**Issue by xPazz** [Timeraa/YT-Presence#10]
`Failed to compile C:/Users/hdpaz/Downloads/YT.Presence/YT Presence-win32-x64/resources/app/index.html: ENOENT: no such file or directory, lstat 'C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\index.html'
Error: ENOENT: no such file or directory, lstat 'C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\index.html'
    at Object.realpathSync (fs.js:1661:15)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:320:29)
    at cachedRealpath (C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\node_modules\electron-compile\lib\sanitize-paths.js:25:22)
    at sanitizeFilePath (C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\node_modules\electron-compile\lib\sanitize-paths.js:52:16)
    at FileChangedCache.getCacheEntryForPath (C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\node_modules\electron-compile\lib\file-change-cache.js:201:48)
    at C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\node_modules\electron-compile\lib\file-change-cache.js:127:41
    at Generator.next (<anonymous>)
    at step (C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\node_modules\electron-compile\lib\file-change-cache.js:27:191)
    at C:\Users\hdpaz\Downloads\YT.Presence\YT Presence-win32-x64\resources\app\node_modules\electron-compile\lib\file-change-cache.js:27:437
    at new Promise (<anonymous>)`

I think you've messed up the paths in your code somewhere..

**Comment by Timeraa** [comment]
Should be fixed in V1.0 (might be releasing in a few hours) As i know it was an error when you ran the program twice. Check if its running twice.

**Comment by xPazz** [comment]
No, I've only got one instance running. This happend on the first launch, and I've tried killing the process and starting again. Same error.

**Comment by Timeraa** [comment]
Hm, ill make Version 1.0 as a Prerelease so that you can try it with that version. Give me a few seconds 😉

**Comment by xPazz** [comment]
I found a weird thing -- It launches two processes..

**Comment by Timeraa** [comment]
Yeah i am still looking into that one but it should work, try using Version 1.0 https://github.com/Timeraa/YT-Presence/releases/tag/v1.0 and maybe join my Discord server https://discord.gg/Kw7WaYn

**Comment by Timeraa** [comment]
Fixed in V1.0
